# NumPy II: Matrizes (Arrays N-dimensionais)

---

## 🎯 Objetivos da Aula

Ao final desta aula, o aluno será capaz de:

1. Explicar o conceito de arrays n-dimensionais e identificar situações em Data Science onde matrizes são necessárias.
2. Criar matrizes 2D usando `np.array()`, `np.zeros()`, `np.ones()`, `np.eye()` e `np.random.rand()`, e inspecionar seus atributos `shape`, `ndim`, `dtype` e `size`.
3. Remodelar e achatar matrizes com `reshape()` e `flatten()`.
4. Acessar elementos, linhas, colunas e submatrizes usando indexação e fatiamento 2D.
5. Realizar operações matriciais — soma, subtração, multiplicação element-wise e produto matricial com `np.dot()` — e transpor matrizes com `.T`.

---

## 🔥 Aquecimento — Problema Gerador (10 min)

Você já abriu uma planilha Excel com dados de vendas? Imagine uma tabela com 12 colunas (uma para cada mês do ano) e 500 linhas (uma para cada loja de uma rede). Para calcular o total anual de cada loja, você soma a linha inteira. Para saber como foi o mês de julho em todas as lojas, você olha a coluna inteira. Para comparar as lojas do Sudeste no segundo semestre, você recorta um pedaço da tabela.

Essa tabela — com linhas e colunas — é exatamente o que chamamos de **matriz** em NumPy.

Na Aula 2, você aprendeu a trabalhar com uma única coluna de dados (array 1D). Mas dados reais raramente chegam em uma única coluna. Eles chegam em tabelas, imagens, cubos de dados, séries temporais multivariadas. Um dataset de filmes tem título, ano, nota, bilheteria — várias colunas ao mesmo tempo. Uma imagem digital é uma matriz de pixels, com linhas e colunas de cores. Um modelo de Machine Learning recebe uma matriz de features (características) onde cada linha é um cliente e cada coluna é um atributo.

**Como representar e operar sobre esses dados bidimensionais de forma eficiente?**

É exatamente isso que você vai aprender hoje: trabalhar com matrizes no NumPy — a estrutura de dados que está por baixo de praticamente todo algoritmo de Data Science.

---

## 📖 Bloco Teórico + Analogias (40 min)

### O que são Arrays N-dimensionais?

Na Aula 2 você trabalhou com arrays **1D** — uma sequência linear de números, como uma única coluna de uma planilha. Hoje subimos um degrau: arrays **2D** (matrizes), que têm linhas e colunas — como a planilha inteira.

O NumPy suporta arrays com qualquer número de dimensões (por isso "N-dimensional"):

| Dimensões | Nome usual | Analogia |
|-----------|-----------|---------|
| 1D | Array / Vetor | Uma coluna de planilha |
| 2D | Matriz | A planilha inteira (linhas × colunas) |
| 3D | Cubo de dados | Várias planilhas empilhadas |
| 4D+ | Tensor | Cubos ao longo do tempo (vídeo, por exemplo) |

> 🏢 **Analogia do prédio:** Um array 1D é um corredor (só tem comprimento). Um array 2D é um andar do prédio (tem comprimento e largura). Um array 3D é o prédio inteiro (comprimento, largura e altura). O NumPy consegue trabalhar com qualquer número de "dimensões" do prédio.

Em Data Science, você vai trabalhar principalmente com 1D e 2D. Mas saber que o conceito existe para mais dimensões é importante — quando você trabalhar com imagens ou redes neurais, vai encontrar arrays 3D e 4D.

---

### Criação de Matrizes

Há cinco formas principais de criar matrizes:

#### `np.array()` com lista de listas

A forma mais direta: cada lista interna vira uma linha da matriz. Todas as listas internas devem ter o mesmo tamanho.

> 📊 **Analogia da planilha:** É como digitar uma tabela no Excel linha por linha. Cada lista interna é uma linha digitada.




### Passo 1: Criando matrizes com `np.array()` 2D

In [26]:
import numpy as np

vendas = np.array([
    [100, 150, 200, 250],    # Produto A : semanas 1, 2, 3, 4
    [120, 180, 240, 230],    # Produto B
    [130, 195, 260, 280]     # Produto C
])

print(vendas)
print(type(vendas))

[[100 150 200 250]
 [120 180 240 230]
 [130 195 260 280]]
<class 'numpy.ndarray'>


---

### Atributos das Matrizes

Os mesmos quatro atributos da Aula 2 funcionam para matrizes, mas agora com informações bidimensionais:

| Atributo | Array 1D | Matriz 2D |
|----------|----------|-----------|
| `.shape` | `(5,)` | `(3, 4)` → 3 linhas, 4 colunas |
| `.ndim` | `1` | `2` |
| `.dtype` | `int64` | `float64` |
| `.size` | `5` | `12` → 3 × 4 |

> 📐 **Regra de leitura do shape:** Em `(3, 4)`, o primeiro número é sempre o número de **linhas** e o segundo é o número de **colunas**. Pense: "3 linhas com 4 elementos cada".

---



### Passo 2: Inspecionando atributos da matriz

In [27]:
print("shape: ", vendas.shape)
print("ndim: ", vendas.ndim)
print("dtype: ", vendas.dtype)
print("size: ", vendas.size)

shape:  (3, 4)
ndim:  2
dtype:  int32
size:  12


### Passo 3: Criando matrizes especiais

#### `np.zeros()` | `np.ones()` | `np.full()` com tupla de dimensões

Agora, em vez de passar um número (como na Aula 2), você passa uma **tupla** com `(linhas, colunas)` para criar uma matriz inteira preenchida com zeros ou uns.



In [28]:
mat_zeros = np.zeros((4,3))
print("Matriz de zeros: \n", mat_zeros)

mat_ones = np.ones((4,3))
print("Matriz de um: \n", mat_ones)

mat_full = np.full((4,3), 7)
print("Matriz de sete: \n", mat_full)

Matriz de zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de um: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriz de sete: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


#### `np.eye()` — Matriz Identidade

Cria uma matriz quadrada com 1s na diagonal principal e 0s em todo o resto. Muito usada em álgebra linear e algoritmos de Machine Learning.

> 🪞 **Analogia do espelho:** A matriz identidade é o "neutro" da multiplicação matricial — multiplicar qualquer matriz pela identidade retorna a própria matriz, assim como multiplicar qualquer número por 1 retorna o próprio número.



In [29]:
mat_ident = np.eye(4)
print("Matriz identidade: \n", mat_ident)

Matriz identidade: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### `np.random.rand()` — Matriz de valores aleatórios

Cria uma matriz preenchida com números aleatórios entre 0 e 1. Indispensável para inicializar pesos de modelos, gerar dados de teste e simulações.

> 🎲 **Analogia do dado:** É como lançar um dado de infinitas faces para cada célula da tabela e anotar o resultado. Cada vez que você executa, os valores mudam.

In [30]:
#np.random.seed(42)  # Para resultados reprodutíveis
mat_aleatoria = np.random.rand(4,3)
print("Matriz aleatória: \n", mat_aleatoria.round(2))


Matriz aleatória: 
 [[0.07 0.14 0.47]
 [0.38 0.96 0.79]
 [0.86 0.05 0.01]
 [0.64 0.9  0.12]]


In [31]:
mat_alet = np.random.uniform(0, 10, (4,3))
print("Matriz aleatória entre 0 e 10: \n", mat_alet.round(2))

Matriz aleatória entre 0 e 10: 
 [[6.99 4.56 4.84]
 [2.86 5.55 7.24]
 [4.55 6.48 2.55]
 [2.29 6.05 3.02]]


### `reshape()` e `flatten()`

**`reshape()`** reorganiza os dados de um array em novas dimensões, **sem alterar os valores** nem a quantidade de elementos. É como reorganizar os móveis de um apartamento: os móveis são os mesmos, só a disposição muda.

> 🧩 **Analogia do quebra-cabeça:** Você tem 12 peças. Pode organizá-las em 3 fileiras de 4, ou em 4 fileiras de 3, ou em 2 fileiras de 6 — as peças são sempre as mesmas, só o formato da mesa muda. A única regra: o total de peças deve ser o mesmo.

**`flatten()`** faz o caminho inverso: transforma qualquer matriz de volta em um array 1D. É como empilhar todas as linhas de uma planilha em uma única coluna longa.

> 📜 **Analogia do rolo de papiro:** Você pega uma planilha retangular (2D) e a "enrola" em um papiro linear (1D).

---



### Passo 4: `reshape()`  — reorganizando dimensões

In [32]:
seq = np.arange(1,13)
print("Sequência de 1 a 12: ", seq)
print("shape: ", seq.shape)

matriz_3x4 = seq.reshape(3,4)
print("Matriz 3x4: \n", matriz_3x4)

matriz_4x3 = seq.reshape(4,3)
print("Matriz 4x3: \n", matriz_4x3)

matriz_2x = seq.reshape(2, -1)
print("Matriz 2x: \n", matriz_2x)

matriz_2x = seq.reshape(-1, 3)
print("Matriz 2x: \n", matriz_2x)





Sequência de 1 a 12:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape:  (12,)
Matriz 3x4: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz 4x3: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matriz 2x: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Matriz 2x: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Passo 5: `flatten()` — achatando de volta para 1D

## ✏️ Exercícios de Fixação

### Exercício 1 — Fácil: Criando e inspecionando matrizes

**Enunciado:** Crie as seguintes matrizes e exiba o `shape`, `ndim` e `size` de cada uma:

a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).  
b) Uma matriz de zeros com 4 linhas e 2 colunas.  
c) A matriz identidade de tamanho 3.

> 💡 **Dica:** Para o item (a), crie primeiro o array com `np.arange(1, 10)` e depois use `.reshape(3, 3)`.


---

### Exercício 3 — Médio: Reshape, flatten e estatísticas por eixo

**Enunciado:** Você tem as vendas mensais de uma loja ao longo de um ano, registradas em um array 1D de 12 elementos (Janeiro a Dezembro):

```python
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
```

1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.
2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
4. Identifique o trimestre com maior faturamento.
5. Use `flatten()` para recuperar o array original.

> 💡 **Dica:** Para o item 4, use `np.argmax()` no array de totais. Lembre que o índice retornado começa em 0 — some 1 para obter o número do trimestre.



In [33]:
# Exercício 1
#a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).
a = np.arange(1, 10).reshape(3,3)
print("Matriz 3x3: \n", a)
print(f' shape: {a.shape}, ndim: {a.ndim}, size: {a.size}')

#b) Uma matriz de zeros com 4 linhas e 2 colunas.  
matriz_zero = np.zeros((4,2))
print(matriz_zero)
print(f' shape: {matriz_zero.shape}, ndim: {matriz_zero.ndim}, size: {matriz_zero.size}')

#c) A matriz identidade de tamanho 3.
matrizidentidade=np.eye(3)
print(matrizidentidade)
print(f' shape: {matrizidentidade.shape}, ndim: {matrizidentidade.ndim}, size: {matrizidentidade.size}')


Matriz 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 shape: (3, 3), ndim: 2, size: 9
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
 shape: (4, 2), ndim: 2, size: 8
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 shape: (3, 3), ndim: 2, size: 9


In [34]:
#1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.

vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])

vendas_trimestre = np.reshape(vendas_ano, (4, 3))
print("Vendas por trimestre: \n", vendas_trimestre)

#5. Use `flatten()` para recuperar o array original.
matriz_achatada = vendas_trimestre.flatten()
print("Matriz achatada: \n", matriz_achatada)

Vendas por trimestre: 
 [[45 52 48]
 [60 55 70]
 [80 78 65]
 [58 50 90]]
Matriz achatada: 
 [45 52 48 60 55 70 80 78 65 58 50 90]


### Indexação e Fatiamento em Matrizes

Em arrays 1D, o índice era um único número. Em matrizes 2D, são **dois números separados por vírgula**: `matriz[linha, coluna]`.

- **Um elemento:** `matriz[2, 3]` → linha 2, coluna 3
- **Uma linha inteira:** `matriz[1, :]` → linha 1, todas as colunas (o `:` significa "tudo")
- **Uma coluna inteira:** `matriz[:, 2]` → todas as linhas, coluna 2
- **Uma submatriz:** `matriz[0:2, 1:3]` → linhas 0-1, colunas 1-2

> 🗺️ **Analogia do mapa do tesouro:** Para encontrar um tesouro no mapa, você precisa de dois valores: latitude e longitude. `matriz[linha, coluna]` funciona igual — dois "endereços" para chegar a um elemento específico.

---



### Passo 6: Indexação e fatiamento em matrizes

In [35]:
#" Matriz de notas: 4 alunos e 3 provas"
notas = np.array([
    [8.5, 7.0, 9.0],   # Aluno 0 : provas 1, 2, 3
    [6.0, 8.0, 7.5],   # Aluno 1
    [9.0, 9.5, 10.0],  # Aluno 2
    [5.5, 6.0, 6.5]    # Aluno 3
])

# Acessando um único elemento da matriz (Nota do Aluno 1 na Prova 2)
val_unico = notas[1,1]
print("Nota do Aluno 1 na Prova 2: ", val_unico)

# Acessando uma linha inteira
print("notas do Aluno 2: ", notas[2, :])

# Acessando uma coluna inteira
print("Notas da Prova 3: ", notas[:,2])

#submatriz: Notas dos Alunos 0 e 1 nas Provas 2 e 3
submatriz = notas[0:2, 1:3]
print("Submatriz (Alunos 0 e 1, Provas 2 e 3): \n", submatriz)

# Usando índice negativo para acessar a última prova do último aluno
ultima_nota = notas[-1, -1]
print("Última nota (Aluno 3, Prova 3): ", ultima_nota)

print("Ultima linha: ", notas[-1, :])

Nota do Aluno 1 na Prova 2:  8.0
notas do Aluno 2:  [ 9.   9.5 10. ]
Notas da Prova 3:  [ 9.   7.5 10.   6.5]
Submatriz (Alunos 0 e 1, Provas 2 e 3): 
 [[7.  9. ]
 [8.  7.5]]
Última nota (Aluno 3, Prova 3):  6.5
Ultima linha:  [5.5 6.  6.5]


### Exercício 2 — Fácil: Indexação e fatiamento

**Enunciado:** Dada a matriz de temperaturas diárias de 3 cidades ao longo de 5 dias:

```python
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])
```

Extraia:
- A temperatura da Cidade B no 3º dia (índice 2).
- Todas as temperaturas da Cidade C.
- As temperaturas de todas as cidades no último dia.
- A submatriz das cidades A e B nos primeiros 3 dias.

> 💡 **Dica:** Para "último dia", use índice `-1` na coluna. Para a submatriz, lembre que o fim do slice é exclusivo.

----

In [36]:
import numpy as np

temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])

#- A temperatura da Cidade B no 3º dia (índice 2).
CidadeB_Dia3 = temperaturas[1,2]
print(f"A temperatura da cidade B no dia 3 foi ",CidadeB_Dia3)

#- Todas as temperaturas da Cidade C.
print(temperaturas[2, :])

#- As temperaturas de todas as cidades no último dia.
print("Último dia:",temperaturas[:, -1])

#- A submatriz das cidades A e B nos primeiros 3 dias.
print('Temperaturas das Cidades A e B do primeiro ao terceiro dia: \n', temperaturas[0:2, 0:3])

A temperatura da cidade B no dia 3 foi  30
[22 24 21 23 25]
Último dia: [35 29 25]
Temperaturas das Cidades A e B do primeiro ao terceiro dia: 
 [[32 33 31]
 [28 27 30]]


### Operações Matriciais

As operações entre matrizes de mesmo tamanho funcionam **element-wise** (elemento a elemento), assim como nos arrays 1D:

- `A + B` → soma elemento por elemento
- `A - B` → subtração elemento por elemento
- `A * B` → multiplicação elemento por elemento (**NÃO é o produto matricial!**)

O **produto matricial** (multiplicação "de verdade" entre matrizes, como na matemática) é feito com `np.dot(A, B)` ou com o operador `@`.

> ⚽ **Analogia do futebol:** `A * B` é como comparar dois times jogador por jogador, posição por posição (zagueiro vs zagueiro, atacante vs atacante). `np.dot(A, B)` é o jogo de verdade — cada jogador de um time interage com todos os do outro time.

**Regra do produto matricial:** Para multiplicar A por B com `np.dot()`, o número de **colunas de A** deve ser igual ao número de **linhas de B**.

---



### Passo 7: Operações matriciais element-wise e broadcasting

In [37]:
import numpy as np

# Faturamento de 3 lojas em 2 semestres
faturamento = np.array([
    [150, 180],         #Loja A : 1º e 2º semestre
    [200, 220],         #Loja B
    [130, 160]          #Loja C
])

#Custo por semestre para cada loja
custo = np.array([
    [80, 90],
    [110, 115],
    [70, 85]
])

# Resultado do Lucro por semestre para cada loja
lucro = faturamento - custo
print ("Lucro por semestre para cada loja: \n", lucro)

# Aplicar uma meta de crescimento de 10% no faturamento.
meta = faturamento *1.10
print("Meta de crescimento de 10% no faturamento: \n", meta)

# Estatísticas por eixo
# axis=0: Operação ao longo das colunas (por semestre)
# axis=1: Operação ao longo das linhas (por loja)
print("\n Total por semestre (axis=0): ", np.sum(faturamento, axis=0))
print("\n Total por loja (axis-1):",  np.sum(faturamento, axis=1))
print("\n Média por loja (axis-1):",  np.mean(faturamento, axis=1))




Lucro por semestre para cada loja: 
 [[ 70  90]
 [ 90 105]
 [ 60  75]]
Meta de crescimento de 10% no faturamento: 
 [[165. 198.]
 [220. 242.]
 [143. 176.]]

 Total por semestre (axis=0):  [480 560]

 Total por loja (axis-1): [330 420 290]

 Média por loja (axis-1): [165. 210. 145.]


### Passo 8: Produto matricial com `np.dot()`


In [38]:
# Cenário: calcular receita total das lojas
# Matriz de quantidades vendidas: 2 x 3 (2 lojas, 3 produto)

quantidade = np.array([
    [100, 50, 200],     # Loja A : Produto 1, 2, 3
    [80, 70, 150]       # Loja B

])

# Criando arrya de preços (vetor)
precos = np.array([25, 40, 15])

# Produto  matricial: (2, 3) x (3,)
# Cada loja: soma de (qtd_prod1 * preco_prod1) + (qtd_prod2 * preco_prod2) + (qtd_prod3 * preco_prod3
receita = np.dot(quantidade, precos)
print("Receita total por loja: ", receita)


# Multiplicação de matrizes vs produto matricial
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

produto_elementwise = A * B
print("Produto elementwise: \n", produto_elementwise)

produto_matricuial = np.dot(A, B)
print("Produto matricial (dot): \n", produto_matricuial)


# Primeira linha de A * Primeira coluna de B: (1*5) + (2*7) = 5 + 14 = 19
# Primeira linha de A * Segunda coluna de B: (1*6) + (2*8) = 6 + 16 = 22
# Segunda linha de A * Primeira coluna de B: (3*5) + (4*7) = 15 + 28 = 43
# Segunda linha de A * Segunda coluna de B: (3*6) + (4*8) = 18 + 32 = 50








Receita total por loja:  [7500 7050]
Produto elementwise: 
 [[ 5 12]
 [21 32]]
Produto matricial (dot): 
 [[19 22]
 [43 50]]


### Transposição: `.T`

Transpor uma matriz significa trocar linhas por colunas. O que era a linha 0 vira a coluna 0, o que era a linha 1 vira a coluna 1, e assim por diante. Uma matriz `(3, 4)` transposta vira `(4, 3)`.

> 🔄 **Analogia da planilha virada:** Imagine uma planilha com meses nas colunas e lojas nas linhas. Transpor é como "virar a planilha de lado": agora os meses ficam nas linhas e as lojas nas colunas. Os dados são os mesmos — só a perspectiva mudou.

Em Data Science, transpor é essencial para alinhar dimensões antes de multiplicações matriciais e para reformatar dados para entrada em modelos.


### Passo 9: Transposição com `.T`

In [39]:
# Matriz de alunos po disciplina: 3 alunos e 4 disciplinas

notas_alunos = np.array([
    [8.5, 7.0, 9.0, 6.5],   # Aluno 0 : disciplinas 1, 2, 3, 4
    [6.0, 8.0, 7.5, 9.0],   # Aluno 1
    [9.0, 9.5, 10.0, 8.0]   # Aluno 2
])

print("Matriz Original de Notas dos Alunos: \n", notas_alunos)
print("Shape original da matrix: ", notas_alunos.shape)

transp = notas_alunos.T
print("Matriz transposta de Notas dos Alunos: \n", transp)
print("Shape original da matrix: ", transp.shape)

Matriz Original de Notas dos Alunos: 
 [[ 8.5  7.   9.   6.5]
 [ 6.   8.   7.5  9. ]
 [ 9.   9.5 10.   8. ]]
Shape original da matrix:  (3, 4)
Matriz transposta de Notas dos Alunos: 
 [[ 8.5  6.   9. ]
 [ 7.   8.   9.5]
 [ 9.   7.5 10. ]
 [ 6.5  9.   8. ]]
Shape original da matrix:  (4, 3)


### Exercício 4 — Médio: Operações e transposição

**Enunciado:** Uma escola tem as notas de 3 alunos em 4 matérias:

```python
notas = np.array([
    [7.0, 8.5, 6.0, 9.0],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])
```

Responda **sem usar laços `for`**:

1. Calcule a média de cada aluno (média por linha).
2. Transpose a matriz e calcule a média de cada matéria (que agora são as linhas).
3. Calcule a diferença entre as notas do Aluno 1 e do Aluno 2 (element-wise).
4. Aplique um bônus de +0.5 em todas as notas (broadcasting). Certifique-se que nenhuma nota ultrapasse 10 usando `np.clip()` — pesquise como funciona!

> 💡 **Dica para o item 4:** `np.clip(array, min, max)` limita os valores de um array entre um mínimo e máximo. O que acontece se a nota já for 9.8 e você somar 0.5?

---

### Exercício 5 — Desafio: Mini Análise de Dataset com Matrizes

**Enunciado:** Uma empresa de e-commerce tem os dados de 5 produtos em 4 regiões do Brasil (Norte, Nordeste, Sudeste, Sul), representando as **quantidades vendidas** no mês:

```python
quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto
```

Resolva **sem usar laços `for`**:

1. Calcule a receita total gerada por cada produto em todas as regiões (soma das colunas de cada linha × preço).
2. Calcule o total de unidades vendidas por região (soma de cada coluna).
3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. *(Dica: use reshape ou broadcasting 2D.)*
5. Exiba a receita total por região.

> 💡 **Dica para o item 4:** Tente `quantidades * precos.reshape(5, 1)` — isso multiplica cada linha pelo preço correspondente daquele produto (broadcasting 2D).

----

In [46]:
import numpy as np 


# Exercício 4:


notas = np.array([
    [7.0, 8.5, 6.0, 9.8],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])


# média por aluno:
print("\n Média por aluno (axis=1):",  np.mean(notas, axis=1))

transp_notas = notas.T
print("Matriz transposta de Notas dos Alunos: \n", transp_notas)

# média por disciplina 
print("\n Média por disciplina (axis=1):",  np.mean(transp_notas, axis=1))

# calcule a diferença entre aluno 1 e 2:

diferenca = notas[0] - notas[1]
print("Diferença entre aluno 1 e 2: \n", diferenca)

# Aplicar um bonus de 0.5 na nota.
bonus = notas + 0.5
print("Nota com Bônus: \n", bonus)

bonus_clip = np.clip(notas + 0.5, 0, 10)
print("Nota com Bônus limitado a 10: \n", bonus_clip)




 Média por aluno (axis=1): [7.825 8.25  7.5  ]
Matriz transposta de Notas dos Alunos: 
 [[7.  9.  6.5]
 [8.5 7.5 9. ]
 [6.  8.  7.5]
 [9.8 8.5 7. ]]

 Média por disciplina (axis=1): [7.5        8.33333333 7.16666667 8.43333333]
Diferença entre aluno 1 e 2: 
 [-2.   1.  -2.   1.3]
Nota com Bônus: 
 [[ 7.5  9.   6.5 10.3]
 [ 9.5  8.   8.5  9. ]
 [ 7.   9.5  8.   7.5]]
Nota com Bônus limitado a 10: 
 [[ 7.5  9.   6.5 10. ]
 [ 9.5  8.   8.5  9. ]
 [ 7.   9.5  8.   7.5]]


In [ ]:
# Exercício 5:
import numpy as np

quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto

receita_produtos = np.sum(quantidades, axis=1) * precos # eixo 1 linha produto
print("Receita total por produto: ", receita_produtos)

produto_por_regiao = quantidades.sum(axis=0)
print("Total de unidades vendidas por região:\n", produto_por_regiao)

soma_produtos = np.sum(quantidades, axis=1) # soma por linha produto]
soma_regioes = np.sum(quantidades, axis=0) # soma por coluna região
produto_mais_vendido = np.argmax(soma_produtos) # produto mais vendido é o que tem a maior soma por linha ele retorna a linha
produto_menos_vendido = np.argmin(soma_produtos)  # produto menos vendido é o que tem a menor soma por linha
regiao_mais_vendida = np.argmax(soma_regioes) # região mais vendida é a que tem a maior soma por coluna
regiao_menos_vendida = np.argmin(soma_regioes) # região menos vendida é a que tem a menor soma por coluna

print(produto_mais_vendido)
print(produto_menos_vendido)
print(regiao_mais_vendida)
print(regiao_menos_vendida)

print(f"Produto mais vendido: Produto {produto_mais_vendido + 1} com {soma_produtos[produto_mais_vendido]} unidades")
print(f"Produto menos vendido: Produto {produto_menos_vendido + 1} com {soma_produtos[produto_menos_vendido]} unidades")
print(f"Região mais vendida: Região {regiao_mais_vendida + 1} com {soma_regioes[regiao_mais_vendida]} unidades")
print(f"Região menos vendida: Região {regiao_menos_vendida + 1} com {soma_regioes[regiao_menos_vendida]} unidades")


precos = precos.reshape(5,1)
print(precos.ndim)

matriz_receitas = quantidades * precos

print(matriz_receitas)


receita_por_regiao = matriz_receitas.sum(axis=0)
print

Receita total por produto:  [46644. 54391. 43780. 57536. 42912.]
Total de unidades vendidas por região:
 [ 760 1500 4320 1790]
4
3
2
0
Produto mais vendido: Produto 5 com 2880 unidades
Produto menos vendido: Produto 4 com 640 unidades
Região mais vendida: Região 3 com 4320 unidades
Região menos vendida: Região 1 com 760 unidades
2
[[ 3588. 10166. 26611.  6279.]
 [ 3992.  7485. 27944. 14970.]
 [ 3980.  8358. 21890.  9552.]
 [ 4495.  8091. 28768. 16182.]
 [ 4619.  7450. 21605.  9238.]]


### ⚠️ Erros Frequentes de Iniciantes

**Erro 1: Passar uma lista simples (não lista de listas) para criar uma matriz**

```python
# ❌ ERRADO: passar uma lista plana quando quer uma matriz
errado = np.array([1, 2, 3, 4, 5, 6])
print(errado.shape)   # (6,) → é 1D, não 2D!

# ✅ CORRETO: usar lista de listas para criar matriz 2D
correto = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(correto.shape)  # (2, 3) → isso sim é uma matriz
```

```
(6,)
(2, 3)
```

---

**Erro 2: Listas internas com tamanhos diferentes**

```python
# ❌ ERRADO: listas internas de tamanhos diferentes
errado = np.array([[1, 2, 3],
                   [4, 5]])    # Linha com 2 elementos quando deveria ter 3!
# Resultado: VisibleDeprecationWarning e dtype=object (não é matriz numérica!)
print(errado.dtype)   # object — problema!

# ✅ CORRETO: todas as linhas com o mesmo número de elementos
correto = np.array([[1, 2, 3],
                    [4, 5, 0]])  # Preencha com 0 se necessário
print(correto.dtype)  # int64
```

```
object
int64
```

---

**Erro 3: `reshape()` com número de elementos incompatível**

```python
arr = np.arange(12)   # 12 elementos

# ❌ ERRADO: tentar fazer reshape para um shape incompatível
# arr.reshape(3, 5)   # 3 × 5 = 15 ≠ 12 → ValueError!

# ✅ CORRETO: o produto das dimensões deve ser igual ao total de elementos
arr_ok = arr.reshape(3, 4)   # 3 × 4 = 12 ✅
arr_ok2 = arr.reshape(2, 6)  # 2 × 6 = 12 ✅
print(arr_ok.shape, arr_ok2.shape)
```

```
(3, 4) (2, 6)
```

---

**Erro 4: Confundir `A * B` com `np.dot(A, B)`**

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 3]])

# ❌ CONFUSÃO: usar * quando quer o produto matricial matemático
print("A * B (element-wise):\n",  A * B)

# ✅ CORRETO: usar np.dot() para o produto matricial "de verdade"
print("np.dot(A, B) (produto matricial):\n", np.dot(A, B))
```

```
A * B (element-wise):
 [[ 2  0]
 [ 3 12]]
np.dot(A, B) (produto matricial):
 [[ 4  6]
 [10 12]]
```

---

**Erro 5: Tentar acessar elemento com índice único em vez de dois índices**

```python
matriz = np.array([[10, 20, 30],
                   [40, 50, 60]])

# ❌ CONFUSÃO: achar que matriz[1] retorna um elemento
print(matriz[1])      # Retorna a LINHA 1 inteira: [40 50 60], não um elemento!

# ✅ CORRETO: usar dois índices para chegar a um único elemento
print(matriz[1, 2])   # Linha 1, coluna 2 → 60
```

```
[40 50 60]
60
```

---


## 🚀 Checkpoint da Jornada

### O que fazer no material de hoje

Esta aula encerra o bloco NumPy do módulo. O mini projeto integrador é o entregável das Aulas 2 e 3 combinadas e deve ser enviado via GIT ao final desta aula.

---

#### Comandos GIT ao finalizar

```bash
git add .
git commit -m "Aulas 02-03: mini projeto NumPy com arrays 1D e matrizes"
git push origin main
```

---

## 🔗 Conexão com a Próxima Aula (5 min)

Você acaba de dominar a estrutura de dados mais fundamental do ecossistema científico Python. Com arrays 1D e matrizes 2D, você já consegue representar e operar sobre praticamente qualquer conjunto de dados numéricos. Mas há um problema: dados reais raramente são só números. Eles têm nomes de colunas, índices com datas, mistura de tipos (texto, número, booleano) e valores faltantes. Na **próxima aula**, você vai conhecer o **Pandas** — a biblioteca que transforma uma matriz NumPy em uma tabela inteligente, com rótulos, tipos mistos e todas as ferramentas para ler, explorar e salvar arquivos de dados do mundo real. É o salto do "laboratório" para o "campo".

---

## 📚 Referências e Recursos

- 📘 [Documentação oficial NumPy — Arrays multidimensionais](https://numpy.org/doc/stable/user/basics.html)
- 🔢 [NumPy: indexação e fatiamento avançado](https://numpy.org/doc/stable/user/basics.indexing.html)
- 📐 [Broadcasting explicado com exemplos visuais](https://numpy.org/doc/stable/user/basics.broadcasting.html)
- 🧮 [np.dot e álgebra linear no NumPy](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- 📊 [np.reshape — documentação com exemplos](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)
- 🎓 [NumPy para Iniciantes — Tutorial oficial completo](https://numpy.org/doc/stable/user/absolute_beginners.html)
- 🇧🇷 [Python para Data Science — NumPy matrizes (Kaggle Learn, gratuito)](https://www.kaggle.com/learn/intro-to-programming)